apiVersion: apps/v1
kind: Deployment
metadata:
  name: doesNotMatter
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: my-security-container
          image: "nginx:latest"
          env:
            - name: SECURITY_SCANNER_KEY
              valueFrom:
                secretKeyRef:
                  key: key
                  name: security-scanner
